package global

type InputConfig struct {
	//Url to connect to
	Url string
	//Authentication string (generated by Authentication.go)
	Authentication string
	//Label to display
	Label string
}

type GlobalConfig struct {
	// Print the time used for image operations
	LogFPS bool
	// Size of the output image
	Width  int
	Height int
	// If images are resized to a weird aspect ratio, should the aspect ratio be forced (true) or be kept the same using letterboxing (false)
	IgnoreAspectRatio bool
	// max framerate for the output
	OutputFramerate float64
	// quality for jpeg encoding
	EncodeQuality int
	// use border between images
	ShowBorder bool
	// parse the authentication.json file for mjpeg-streamer streams using credentials
	UseAuth bool
	// show labels...
	ShowInputLabel bool
	// ...and also change their size
	InputLabelFontSize int
	// enable activity detection for carousel or panel
	UseActivity bool
	// configs for the inputstreams
	InputConfigs []InputConfig
	//hidden
	DisablePassthrough bool
	AlwaysActive       bool
	Debug              bool
}

var Config GlobalConfig

// initialConfig returns the default values to the global fields
func initialConfig() GlobalConfig {
	return GlobalConfig{
		LogFPS:             false,
		Width:              -1,
		Height:             -1,
		IgnoreAspectRatio:  false,
		OutputFramerate:    -1,
		EncodeQuality:      -1,
		ShowBorder:         false,
		UseAuth:            false,
		ShowInputLabel:     false,
		InputLabelFontSize: 32,
		UseActivity:        false,
		InputConfigs:       []InputConfig{},
		//hidden
		DisablePassthrough: false,
		AlwaysActive:       false,
		Debug:              false,
	}
}

// SetupInitialConfig Assigns the default values to the global config
func SetupInitialConfig() {
	Config = initialConfig()
}

// DecodingNecessary checks whether a jpeg image needs to be decoded based on the configs or if a passthrough is possible
func DecodingNecessary() bool {
	return Config.Height != -1 || Config.Width != -1 || (Config.EncodeQuality != 100 && Config.EncodeQuality != -1) || Config.ShowInputLabel || Config.DisablePassthrough
}
