name: Go build and test

on:
  push:
  pull_request:

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/arm64'
            package: 'src'
            compress: 'false'
            dest: 'dist'
            name: 'multiFLEXer'
      - name: Check build dir
        run: ls -lR ./
