name: Build and generate binary

'on':
  push: null
  pull_request: null
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l]
        include:
        - arch: armv7l
          cpu: cortex-a53
          base_image: raspios_lite:latest
          cpu_info: raspberrypi_3b
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          copy_artifact_path: multiplexer_arm
          image_additional_mb: 1024
          base_image: '${{ matrix.base_image }}'
          cpu: '${{ matrix.cpu }}'
          commands: |
            apt-get install --no-install-recommends -y libjpeg62-turbo-dev
            wget 'https://go.dev/dl/go1.18.3.linux-armv6l.tar.gz'
            sudo tar -C /usr/local -xzf go1.18.3.linux-armv6l.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            export GOPATH=$HOME/go
            pwd
            ls -l
            go build -o multiplexer_arm ./src/main.go 
            ls -l
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: multiplexer_arm
          path: multiplexer_arm
      # release artifact
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Latest
          draft: false
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./multiplexer_arm
          asset_name: multiplexer_arm
          asset_content_type: application/bin
