name: Go build and test

on:
  push:
  pull_request:

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          pkg: src
          prefix: multiplexer
          targets: linux/arm64
          v: true
          x: true
          race: false
          ldflags: -s -w
          buildmode: default
      - name: Check build dir
        run: ls -lR 
      - name: Check build dir
        run: ls -lR /
