name: Build and generate binary

'on':
  push: null
  pull_request: null
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: raspberrypi_3b
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: raspberrypi_zero2_w_arm64_w
    steps:
      - uses: actions/checkout@v2
      - uses: pguyot/arm-runner-action@v2
        with:
          image_additional_mb: 1024
          base_image: '${{ matrix.base_image }}'
          cpu: '${{ matrix.cpu }}'
          commands: |
            apt-get install --no-install-recommends -y libjpeg62-turbo-dev
            wget 'https://go.dev/dl/go1.18.3.linux-arm64.tar.gz'
            sudo tar -C /usr/local -xzf go1.18.3.linux-arm64.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            export GOPATH=$HOME/go
            pwd
            ls -l
            go build -o multiplexer_arm ./src/main.go 
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: Release image
          path: my-release-image.img.xz
