name: Release Go Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm
        project_path: "./src/"
        overwrite: TRUE
